### PR TITLE
feat(RTCGQ02LM): Implement motion timeout

### LINKED ISSUE #32: Issue with RTCGQ02LM
It looks like RTCGQ02LM only send a message when a motion is detected with byte saying if there was some light or not.

On HA side, I only a "light" binary sensor whose state change IF there is a movement AND the light condition change.

Ex: 

- if there is two consecutive motion message with light on, the binary sensor change to "Light detected", but nothing change on the second message.
- if there is one motion message with light on, and a second one with light off, the binary sensor change to "Light detected" on the first message, and "No light" for the second message.
- If only the light change, no change on HA side (and the Light binary sensor seems misleading)

For now, the sensors looks barely useable as a light change condition is needed for motion to be detected.
It seems linked to https://github.com/Bluetooth-Devices/xiaomi-ble/issues/4#issuecomment-1193174456

### PR DESCRIPTION
**Pull request by Alkorin**
RTCGQ02LM sends a Timeout Motion packet after ~30s of inactivity

Fix #32

### CODE REVIEW

**Review by Jc2k — COMMENTED** [review]
Code wise this looks great to me. Thanks for putting it together!

One thing I want to understand - does it send 101b intermittently or only once to clear the motion state? Wondering what would happen if HA "missed" this packet.

If we can "miss" this, then should we just use events and device triggers for the motion event and not have a motion state at all for this device?

**Comment by Alkorin** [comment]
@Jc2k Afaik, it send 101b only once to clear the motion state.
I'll try to capture a full event log

**Comment by Alkorin** [comment]
```
2023-01-15 11:16:10.334 DEBUG (MainThread) [xiaomi_ble.parser] Parsing 18:C2:3C:20:8E:77 adv: 0f0003000100, type: 000f, data 000100
2023-01-15 11:16:35.423 DEBUG (MainThread) [xiaomi_ble.parser] Parsing 18:C2:3C:20:8E:77 adv: 0f0003000100, type: 000ff, data 000100
2023-01-15 11:17:00.314 DEBUG (MainThread) [xiaomi_ble.parser] Parsing 18:C2:3C:20:8E:77 adv: 0f0003000100, type: 000ff, data 000100
2023-01-15 11:17:25.394 DEBUG (MainThread) [xiaomi_ble.parser] Parsing 18:C2:3C:20:8E:77 adv: 0f0003000100, type: 000ff, data 000100
2023-01-15 11:18:00.413 DEBUG (MainThread) [xiaomi_ble.parser] Parsing 18:C2:3C:20:8E:77 adv: 1b10041e000000, type: 101b, data 1e000000
2023-01-15 11:19:25.315 DEBUG (MainThread) [xiaomi_ble.parser] Parsing 18:C2:3C:20:8E:77 adv: 17100478000000, type: 1017, data 78000000
2023-01-15 11:22:25.332 DEBUG (MainThread) [xiaomi_ble.parser] Parsing 18:C2:3C:20:8E:77 adv: 1710042c010000, type: 1017, data 2c010000
```

So it sends 0x000F to set motion state and each 25s if there is still motion.
It sends 0x101B after 30s without motion.
It periodically sends 0x1017 to confirm absence of motion

So the issue of missing the 0x101B packet is the same as missing the first 0x000F packet : lag to catch the new state

**Comment by Ernst79** [comment]
I totally missed this PR. Looks good to me, and should fix https://github.com/home-assistant/core/issues/87296

**Pull request merged**
