### PR TITLE
Support for new Xiaomi lock XMZNMSBMCN03

### PR DESCRIPTION
**Pull request by Ernst79**
Support for new Xiaomi lock XMZNMSBMCN03

### CODE REVIEW

**Comment by Ernst79** [comment]
The problem is that most people are not very keen of giving their encryption key, as it is a lock. So, all i have is already in the BLE monitor tests. Dont have a lock myself either. I can make an overview of all info i know, but Im on a holiday right now, so its a bit difficult to do this on my Phone. I will open a new issue, in which i will try to collect the info, about which lock is using what.

**Comment by Ernst79** [comment]
The locks are all encrypted btw

**Comment by Jc2k** [comment]
No big rush - enjoy your holiday - more of a medium/long term goal.

Might be able to make some tooling that can re-encrypt the test data with a known key. Not as good as real test data, but would be ok to lift our coverage up a bit.

**Comment by Ernst79** [comment]
There is some test data here https://github.com/custom-components/ble_monitor/blob/81f4d5882f72fc6b1b64ea1fb53391a380d1e380/custom_components/ble_monitor/test/test_xiaomi_parser.py#L403

And the next test as well. This lock seems to have no encryption key

**Comment by loganhwang** [comment]
> 
I don't know how to match this lock

**Comment by Jc2k** [comment]
The mapping for locks from this library to home assistant hasn't happened yet, so this is expected. We are still working to support all the known devices. All I can say right now is, please try again in a future release of Home Assistant.

**Pull request merged**
