### PR TITLE
feat: Petoneer Smart Odor Eliminator Pro (SU001-T)

### PR DESCRIPTION
**Pull request by Ernst79**
- Adding Petoneer Smart Odor Eliminator Pro (SU001-T)

I don't have an actual bytestring, so no tests

### CODE REVIEW

**Comment by Ernst79** [comment]
I really have to learn this Lint Commit format....

**Review by Jc2k — APPROVED** [review]

**Comment by Ernst79** [comment]
I'll fix the release notes

**Comment by Ernst79** [comment]
Is that version/release thing all working on its own? I see it now made 0.1.0. Does that mean I won't have to change version numbers anywhere?

**Comment by Jc2k** [comment]
Apparently yes, it bumps the version, updates the changelog, tags, pushes to pypi, everything.

**Comment by Ernst79** [comment]
oh, great. Didn't know that was even possible.

**Pull request merged**
